# Generated by Django 5.0.4 on 2024-06-18 15:02

import blog.models
import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='correo_usuario',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono_usuario',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='CL'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='null', upload_to='productos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), blog.models.validate_image_size]),
        ),
    ]
