# Generated by Django 5.0.4 on 2024-06-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_orden_correo_usuario_orden_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='correo_usuario',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='telefono_usuario',
        ),
    ]
