# Generated by Django 4.2.14 on 2024-12-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
