# Generated by Django 4.2.14 on 2024-12-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.producto'),
        ),
    ]
