# Generated by Django 4.2.14 on 2024-12-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_orden_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='producto',
            new_name='productos',
        ),
    ]
