# Generated by Django 4.2.14 on 2024-12-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_ordenobuma_precio_total_productoobuma_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenobuma',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordenobuma',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ComentarioProducto',
        ),
        migrations.DeleteModel(
            name='OrdenObuma',
        ),
        migrations.DeleteModel(
            name='ProductoObuma',
        ),
    ]
