# Generated by Django 4.2.14 on 2024-12-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
