# Generated by Django 4.2.14 on 2025-01-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_pedido_productopedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productopedido',
            old_name='sku',
            new_name='codigo_comercial',
        ),
    ]
