# Generated by Django 4.2.14 on 2025-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_cliente_productocorreo_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='blog.producto'),
        ),
    ]
