# Generated by Django 4.2.14 on 2025-01-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_pedido_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.DeleteModel(
            name='ProductoCorreo',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
