# Generated by Django 4.2.14 on 2025-01-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_pedido_detalleproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleproducto',
            old_name='sku',
            new_name='producto_codigo_comercial',
        ),
    ]
