# Generated by Django 4.2.14 on 2025-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_rename_sku_detalleproducto_producto_codigo_comercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproducto',
            name='producto_codigo_comercial',
            field=models.CharField(max_length=50, verbose_name='SKU'),
        ),
    ]
